-- Authors: Rafał Wycichowski, Tomasz Baraniecki
-- 7
-- Which languages are growing up and with are falling down?
-- In order to answer this question we will do simple query that will provide us with results we want
-- 09.2013 - 09.2016
SELECT 
l.language as language,
a.sum as "2013-09",
b.sum as "2013-10",
c.sum as "2013-11",
d.sum as "2013-12",
aa.sum as "2014-01",
ab.sum as "2014-02",
ac.sum as "2014-03",
ad.sum as "2014-04",
ae.sum as "2014-05",
af.sum as "2014-06",
ag.sum as "2014-07",
ah.sum as "2014-08",
ai.sum as "2014-09",
aj.sum as "2014-10",
ak.sum as "2014-11",
al.sum as "2014-12",
ba.sum as "2015-01",
bb.sum as "2015-02",
bc.sum as "2015-03",
bd.sum as "2015-04",
be.sum as "2015-05",
bf.sum as "2015-06",
bg.sum as "2015-07",
bh.sum as "2015-08",
bi.sum as "2015-09",
bj.sum as "2015-10",
bk.sum as "2015-11",
bl.sum as "2015-12",
ca.sum as "2016-01",
cb.sum as "2016-02",
cc.sum as "2016-03",
cd.sum as "2016-04",
ce.sum as "2016-05",
cf.sum as "2016-06",
cg.sum as "2016-07",
ch.sum as "2016-08",
ci.sum as "2016-09"
FROM language_dimension as l,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2013 AND month=9 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as a,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2013 AND month=10 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as b,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2013 AND month=1 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as c,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2013 AND month=12 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as d,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=1 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as aa,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=2 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ab,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=3 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ac,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=4 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ad,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=5 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ae,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=6 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as af,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=7 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ag,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=8 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ah,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=9 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ai,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=10 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as aj,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=11 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ak,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2014 AND month=12 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as al,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=1 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ba,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=2 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bb,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=3 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bc,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=4 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bd,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=5 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as be,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=6 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bf,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=7 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bg,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=8 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bh,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=9 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bi,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=10 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bj,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=11 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bk,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2015 AND month=12 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as bl,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2016 AND month=1 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ca,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2016 AND month=2 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as cb,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2016 AND month=3 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as cc,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2016 AND month=4 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as cd,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2016 AND month=5 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ce,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2016 AND month=6 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as cf,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2016 AND month=7 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as cg,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2016 AND month=8 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ch,
(SELECT l, SUM(sum) as sum FROM(SELECT language_id as l, SUM(amount) as sum FROM facts WHERE year=2016 AND month=9 GROUP BY language_id UNION SELECT language, 0 FROM language_dimension) as x GROUP BY l ORDER BY sum desc) as ci
WHERE a.l = l.language AND b.l = l.language AND c.l = l.language AND d.l = l.language AND aa.l = l.language AND ab.l = l.language AND ac.l = l.language AND ad.l = l.language AND ae.l = l.language AND af.l = l.language AND ag.l = l.language AND ah.l = l.language AND ai.l = l.language AND aj.l = l.language AND ak.l = l.language AND al.l = l.language AND ba.l = l.language AND bb.l = l.language AND bc.l = l.language AND bd.l = l.language AND be.l = l.language AND bf.l = l.language AND bg.l = l.language AND bh.l = l.language AND bi.l = l.language AND bj.l = l.language AND bk.l = l.language AND bl.l = l.language AND ca.l = l.language AND cb.l = l.language AND cc.l = l.language AND cd.l = l.language AND ce.l = l.language AND cf.l = l.language AND cg.l = l.language AND ch.l = l.language AND ci.l = l.language 
ORDER BY a.sum desc;
